package uy.org.aladi.admrh.jpadomain.entities;

// Generated 14/05/2015 02:36:18 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Fcabezalrecibos generated by hbm2java
 */
@Entity
@Table(name = "fcabezalrecibos", uniqueConstraints = @UniqueConstraint(columnNames = "Tarjeta"))
public class Fcabezalrecibos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4457493657461775057L;
	private Integer idFcabezalRecibos;
	private Gplanta gplanta;
	private Short tarjeta;
	private String nombre;
	private String sector;
	private BigDecimal cotizacion;
	private String mesLiquidacion;
	private BigDecimal pctDisponible;
	private BigDecimal liquido;
	private BigDecimal adiciones;
	private BigDecimal descuentos;
	private List<Fhaberesliquidados> haberesliquidados = new ArrayList<Fhaberesliquidados>();
	
	
	public Fcabezalrecibos() {
	}

	public Fcabezalrecibos(Gplanta gplanta) {
		this.gplanta = gplanta;
	}

	public Fcabezalrecibos(Gplanta gplanta, Short tarjeta, String nombre,
			String sector, BigDecimal cotizacion, String mesLiquidacion,
			BigDecimal pctDisponible, BigDecimal liquido, BigDecimal adiciones,
			BigDecimal descuentos, List<Fhaberesliquidados> haberesliquidados) {
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
		this.nombre = nombre;
		this.sector = sector;
		this.cotizacion = cotizacion;
		this.mesLiquidacion = mesLiquidacion;
		this.pctDisponible = pctDisponible;
		this.liquido = liquido;
		this.adiciones = adiciones;
		this.descuentos = descuentos;
		this.haberesliquidados = haberesliquidados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFCabezalRecibos", unique = true, nullable = false)
	public Integer getIdFcabezalRecibos() {
		return this.idFcabezalRecibos;
	}

	public void setIdFcabezalRecibos(Integer idFcabezalRecibos) {
		this.idFcabezalRecibos = idFcabezalRecibos;
	}

	@ManyToOne
    @JoinColumn(name="idGPlanta", nullable=false)
    @NotNull
	public Gplanta getGplanta() {
		return gplanta;
	}

	public void setGplanta(Gplanta gplanta) {
		this.gplanta = gplanta;
	}

	@Column(name = "Tarjeta", unique = true)
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "Nombre", length = 50)
	@Size(max = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Sector", length = 100)
	@Size(max = 100)
	public String getSector() {
		return this.sector;
	}

	public void setSector(String sector) {
		this.sector = sector;
	}

	@Column(name = "Cotizacion", precision = 8)
	public BigDecimal getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(BigDecimal cotizacion) {
		this.cotizacion = cotizacion;
	}

	@Column(name = "MesLiquidacion", length = 100)
	@Size(max = 100)
	public String getMesLiquidacion() {
		return this.mesLiquidacion;
	}

	public void setMesLiquidacion(String mesLiquidacion) {
		this.mesLiquidacion = mesLiquidacion;
	}

	@Column(name = "PctDisponible", precision = 8)
	public BigDecimal getPctDisponible() {
		return this.pctDisponible;
	}

	public void setPctDisponible(BigDecimal pctDisponible) {
		this.pctDisponible = pctDisponible;
	}

	@Column(name = "Liquido", precision = 8)
	public BigDecimal getLiquido() {
		return this.liquido;
	}

	public void setLiquido(BigDecimal liquido) {
		this.liquido = liquido;
	}

	@Column(name = "Adiciones", precision = 8)
	public BigDecimal getAdiciones() {
		return this.adiciones;
	}

	public void setAdiciones(BigDecimal adiciones) {
		this.adiciones = adiciones;
	}

	@Column(name = "Descuentos", precision = 8)
	public BigDecimal getDescuentos() {
		return this.descuentos;
	}

	public void setDescuentos(BigDecimal descuentos) {
		this.descuentos = descuentos;
	}

	@OneToMany(mappedBy = "fcabezalrecibos")
	public List<Fhaberesliquidados> getHaberesliquidados() {
		return haberesliquidados;
	}

	public void setHaberesliquidados(List<Fhaberesliquidados> haberesliquidados) {
		this.haberesliquidados = haberesliquidados;
	}


}
