package uy.org.aladi.admrh.jpadomain.entities;
// Generated 12/12/2014 02:43:52 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * Fcodigos generated by hbm2java
 */
@Entity
@Table(name="fcodigos")
public class Fcodigos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 8243272933707552458L;
	private Short idFcodigos;
     private String descripcion;
     private Boolean adicion;
     private Boolean descuento;
     private Short colListLiquidos;
     private Boolean habilitado;
     private String observaciones;

    public Fcodigos() {
    }

    public Fcodigos(String descripcion, Boolean adicion, Boolean descuento, Short colListLiquidos, 
    		Boolean habilitado, String observaciones) {
       this.descripcion = descripcion;
       this.adicion = adicion;
       this.descuento = descuento;
       this.colListLiquidos = colListLiquidos;
       this.habilitado = habilitado;
       this.observaciones = observaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFCodigos", unique=true, nullable=false)
    public Short getIdFcodigos() {
        return this.idFcodigos;
    }
    
    public void setIdFcodigos(Short idFcodigos) {
        this.idFcodigos = idFcodigos;
    }

    
    @Column(name="Descripcion", length=50)
    @Size(max=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="Adicion")
    public Boolean getAdicion() {
        return this.adicion;
    }
    
    public void setAdicion(Boolean adicion) {
        this.adicion = adicion;
    }

    
    @Column(name="Descuento")
    public Boolean getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Boolean descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="ColListLiquidos")
    public Short getColListLiquidos() {
        return this.colListLiquidos;
    }
    
    public void setColListLiquidos(Short colListLiquidos) {
        this.colListLiquidos = colListLiquidos;
    }

    
    @Column(name="Habilitado")
    public Boolean getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(Boolean habilitado) {
        this.habilitado = habilitado;
    }

    @Column(name="Observaciones")
	public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}


}


