package uy.org.aladi.admrh.jpadomain.entities;

// Generated 17/08/2015 01:57:58 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

/**
 * Fcostoaladihist generated by hbm2java
 */
@Entity
@Table(name = "fcostoaladihist", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MesAnio", "Tarjeta" }))
public class Fcostoaladihist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4983563831916725698L;
	private Long idFcostoAladiHist;
	private String mesAnio;
	private Long idGplanta;
	private Short tarjeta;
	private String nombre;
	private BigDecimal basico;
	private BigDecimal aguinaldo;
	private BigDecimal compensa;
	private BigDecimal hextras;
	private BigDecimal excAtFliar;
	private BigDecimal cargas;
	private BigDecimal aporte;
	private BigDecimal antiguedad;
	private BigDecimal vivienda;
	private BigDecimal representacion;
	private BigDecimal segVida;
	private BigDecimal segAccidT;
	private BigDecimal segSalud;
	private BigDecimal otrosMas;
	private BigDecimal otrosMenos;
	private BigDecimal total;

	public Fcostoaladihist() {
	}

	public Fcostoaladihist(Long idGplanta) {
		this.idGplanta = idGplanta;
	}

	public Fcostoaladihist(String mesAnio, Long idGplanta, Short tarjeta,
			String nombre, BigDecimal basico, BigDecimal aguinaldo,
			BigDecimal compensa, BigDecimal hextras, BigDecimal excAtFliar,
			BigDecimal cargas, BigDecimal aporte, BigDecimal antiguedad,
			BigDecimal vivienda, BigDecimal representacion, BigDecimal segVida,
			BigDecimal segAccidT, BigDecimal segSalud, BigDecimal otrosMas,
			BigDecimal otrosMenos, BigDecimal total) {
		this.mesAnio = mesAnio;
		this.idGplanta = idGplanta;
		this.tarjeta = tarjeta;
		this.nombre = nombre;
		this.basico = basico;
		this.aguinaldo = aguinaldo;
		this.compensa = compensa;
		this.hextras = hextras;
		this.excAtFliar = excAtFliar;
		this.cargas = cargas;
		this.aporte = aporte;
		this.antiguedad = antiguedad;
		this.vivienda = vivienda;
		this.representacion = representacion;
		this.segVida = segVida;
		this.segAccidT = segAccidT;
		this.segSalud = segSalud;
		this.otrosMas = otrosMas;
		this.otrosMenos = otrosMenos;
		this.total = total;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFCostoAladiHist", unique = true, nullable = false)
	public Long getIdFcostoAladiHist() {
		return this.idFcostoAladiHist;
	}

	public void setIdFcostoAladiHist(Long idFcostoAladiHist) {
		this.idFcostoAladiHist = idFcostoAladiHist;
	}

	@Column(name = "MesAnio", length = 7)
	@Size(max = 7)
	public String getMesAnio() {
		return this.mesAnio;
	}

	public void setMesAnio(String mesAnio) {
		this.mesAnio = mesAnio;
	}

	@Column(name = "idGPlanta", nullable = false)
	public Long getIdGplanta() {
		return this.idGplanta;
	}

	public void setIdGplanta(Long idGplanta) {
		this.idGplanta = idGplanta;
	}

	@Column(name = "Tarjeta")
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "Nombre", length = 60)
	@Size(max = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Basico", precision = 10)
	public BigDecimal getBasico() {
		return this.basico;
	}

	public void setBasico(BigDecimal basico) {
		this.basico = basico;
	}

	@Column(name = "Aguinaldo", precision = 8)
	public BigDecimal getAguinaldo() {
		return this.aguinaldo;
	}

	public void setAguinaldo(BigDecimal aguinaldo) {
		this.aguinaldo = aguinaldo;
	}

	@Column(name = "Compensa", precision = 8)
	public BigDecimal getCompensa() {
		return this.compensa;
	}

	public void setCompensa(BigDecimal compensa) {
		this.compensa = compensa;
	}

	@Column(name = "HExtras", precision = 8)
	public BigDecimal getHextras() {
		return this.hextras;
	}

	public void setHextras(BigDecimal hextras) {
		this.hextras = hextras;
	}

	@Column(name = "ExcAtFliar", precision = 8)
	public BigDecimal getExcAtFliar() {
		return this.excAtFliar;
	}

	public void setExcAtFliar(BigDecimal excAtFliar) {
		this.excAtFliar = excAtFliar;
	}

	@Column(name = "Cargas", precision = 8)
	public BigDecimal getCargas() {
		return this.cargas;
	}

	public void setCargas(BigDecimal cargas) {
		this.cargas = cargas;
	}

	@Column(name = "Aporte", precision = 8)
	public BigDecimal getAporte() {
		return this.aporte;
	}

	public void setAporte(BigDecimal aporte) {
		this.aporte = aporte;
	}

	@Column(name = "Antiguedad", precision = 8)
	public BigDecimal getAntiguedad() {
		return this.antiguedad;
	}

	public void setAntiguedad(BigDecimal antiguedad) {
		this.antiguedad = antiguedad;
	}

	@Column(name = "Vivienda", precision = 8)
	public BigDecimal getVivienda() {
		return this.vivienda;
	}

	public void setVivienda(BigDecimal vivienda) {
		this.vivienda = vivienda;
	}

	@Column(name = "Representacion", precision = 8)
	public BigDecimal getRepresentacion() {
		return this.representacion;
	}

	public void setRepresentacion(BigDecimal representacion) {
		this.representacion = representacion;
	}

	@Column(name = "SegVida", precision = 8)
	public BigDecimal getSegVida() {
		return this.segVida;
	}

	public void setSegVida(BigDecimal segVida) {
		this.segVida = segVida;
	}

	@Column(name = "SegAccidT", precision = 8)
	public BigDecimal getSegAccidT() {
		return this.segAccidT;
	}

	public void setSegAccidT(BigDecimal segAccidT) {
		this.segAccidT = segAccidT;
	}

	@Column(name = "SegSalud", precision = 8)
	public BigDecimal getSegSalud() {
		return this.segSalud;
	}

	public void setSegSalud(BigDecimal segSalud) {
		this.segSalud = segSalud;
	}

	@Column(name = "OtrosMas", precision = 8)
	public BigDecimal getOtrosMas() {
		return this.otrosMas;
	}

	public void setOtrosMas(BigDecimal otrosMas) {
		this.otrosMas = otrosMas;
	}

	@Column(name = "OtrosMenos", precision = 8)
	public BigDecimal getOtrosMenos() {
		return this.otrosMenos;
	}

	public void setOtrosMenos(BigDecimal otrosMenos) {
		this.otrosMenos = otrosMenos;
	}

	@Column(name = "Total", precision = 8)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

}
