package uy.org.aladi.admrh.jpadomain.entities;

// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ffonasa generated by hbm2java
 */
@Entity
@Table(name = "ffonasa")
public class Ffonasa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6819237960556100640L;
	private Short idFfonasa;
	private Short edadDesde;
	private Short edadHasta;
	private BigDecimal hombres;
	private BigDecimal mujeres;

	public Ffonasa() {
	}

	public Ffonasa(Short edadDesde, Short edadHasta) {
		this.edadDesde = edadDesde;
		this.edadHasta = edadHasta;
	}

	public Ffonasa(Short edadDesde, Short edadHasta, BigDecimal hombres,
			BigDecimal mujeres) {
		this.edadDesde = edadDesde;
		this.edadHasta = edadHasta;
		this.hombres = hombres;
		this.mujeres = mujeres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFFonasa", unique = true, nullable = false)
	public Short getIdFfonasa() {
		return this.idFfonasa;
	}

	public void setIdFfonasa(Short idFfonasa) {
		this.idFfonasa = idFfonasa;
	}

	@Column(name = "EdadDesde", nullable = false)
	public Short getEdadDesde() {
		return this.edadDesde;
	}

	public void setEdadDesde(Short edadDesde) {
		this.edadDesde = edadDesde;
	}

	@Column(name = "EdadHasta", nullable = false)
	public Short getEdadHasta() {
		return this.edadHasta;
	}

	public void setEdadHasta(Short edadHasta) {
		this.edadHasta = edadHasta;
	}

	@Column(name = "Hombres", precision = 8)
	public BigDecimal getHombres() {
		return this.hombres;
	}

	public void setHombres(BigDecimal hombres) {
		this.hombres = hombres;
	}

	@Column(name = "Mujeres", precision = 8)
	public BigDecimal getMujeres() {
		return this.mujeres;
	}

	public void setMujeres(BigDecimal mujeres) {
		this.mujeres = mujeres;
	}

}
