package uy.org.aladi.admrh.jpadomain.entities;

// Generated 17/07/2015 02:41:00 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Fhaberesliquidados generated by hbm2java
 */
@Entity
@Table(name = "fhaberesliquidados")
public class Fhaberesliquidados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2223412212430390414L;
	private Long idFhaberesLiquidados;
	private Gplanta gplanta;
	private Short tarjeta;
	private String mesLiquidacion;
	private Fcabezalrecibos fcabezalrecibos; 
	private Fcodigos fcodigos;
	private Integer orden;
	private String descripcion;
	private Short sumaResta;
	private Short cantidad;
	private BigDecimal importe;
	private String moneda;
	private Short registro;

	public Fhaberesliquidados() {
	}

	public Fhaberesliquidados(Gplanta gplanta, Fcabezalrecibos fcabezalRecibos,
			Fcodigos fcodigos) {
		this.gplanta = gplanta;
		this.fcabezalrecibos = fcabezalRecibos;
		this.fcodigos = fcodigos;
	}

	public Fhaberesliquidados(Gplanta gplanta, Short tarjeta,
			String mesLiquidacion, Fcabezalrecibos fcabezalRecibos, Fcodigos fcodigos,
			Integer orden, String descripcion, Short sumaResta, Short cantidad,
			BigDecimal importe, String moneda, Short registro) {
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
		this.mesLiquidacion = mesLiquidacion;
		this.fcabezalrecibos = fcabezalRecibos;
		this.fcodigos = fcodigos;
		this.orden = orden;
		this.descripcion = descripcion;
		this.sumaResta = sumaResta;
		this.cantidad = cantidad;
		this.importe = importe;
		this.moneda = moneda;
		this.registro = registro;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFHaberesLiquidados", unique = true, nullable = false)
	public Long getIdFhaberesLiquidados() {
		return this.idFhaberesLiquidados;
	}

	public void setIdFhaberesLiquidados(Long idFhaberesLiquidados) {
		this.idFhaberesLiquidados = idFhaberesLiquidados;
	}

	@ManyToOne
    @JoinColumn(name="idGPlanta", nullable=false)
    @NotNull
	public Gplanta getGplanta() {
		return gplanta;
	}

	public void setGplanta(Gplanta gplanta) {
		this.gplanta = gplanta;
	}

	@Column(name = "Tarjeta")
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "MesLiquidacion", length = 6)
	@Size(max = 6)
	public String getMesLiquidacion() {
		return this.mesLiquidacion;
	}

	public void setMesLiquidacion(String mesLiquidacion) {
		this.mesLiquidacion = mesLiquidacion;
	}

	@ManyToOne
    @JoinColumn(name="idFCabezalRecibos", nullable=false)
    @NotNull
	public Fcabezalrecibos getFcabezalrecibos() {
		return fcabezalrecibos;
	}

	public void setFcabezalrecibos(Fcabezalrecibos fcabezalrecibos) {
		this.fcabezalrecibos = fcabezalrecibos;
	}


	@ManyToOne
    @JoinColumn(name="idFCodigos", nullable=false)
    @NotNull
	public Fcodigos getFcodigos() {
		return fcodigos;
	}

	public void setFcodigos(Fcodigos fcodigos) {
		this.fcodigos = fcodigos;
	}

	@Column(name = "Orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "Descripcion", length = 50)
	@Size(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SumaResta")
	public Short getSumaResta() {
		return this.sumaResta;
	}

	public void setSumaResta(Short sumaResta) {
		this.sumaResta = sumaResta;
	}

	@Column(name = "Cantidad")
	public Short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Short cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "Importe", precision = 8)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "Moneda", length = 7)
	@Size(max = 7)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "Registro")
	public Short getRegistro() {
		return this.registro;
	}

	public void setRegistro(Short registro) {
		this.registro = registro;
	}
}
