package uy.org.aladi.admrh.jpadomain.entities;

// Generated 08/04/2015 01:32:23 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * Fhabereshist generated by hbm2java
 */
@Entity
@Table(name = "fhabereshist")
public class Fhabereshist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -277400459108231141L;
	private Long idFhaberesHist;
	private long idGplanta;
	private Short tarjeta;
	private String mesLiquidacion;
	private Integer idFCabezalRecibosHist;
	private Short idFcodigos;
	private Integer orden;
	private String descripcion;
	private Short sumaResta;
	private Short cantidad;
	private BigDecimal importe;
	private String moneda;
	private Short registro;

	public Fhabereshist() {
	}

	public Fhabereshist(long idGplanta) {
		this.idGplanta = idGplanta;
	}

	public Fhabereshist(long idGplanta, Short tarjeta, String mesLiquidacion, Integer idFcabezalRecibosHist, 
			Short idFcodigos, Integer orden, String descripcion,
			Short sumaResta, Short cantidad, BigDecimal importe, String moneda,
			Short registro) {
		this.idGplanta = idGplanta;
		this.tarjeta = tarjeta;
		this.mesLiquidacion = mesLiquidacion;
		this.idFCabezalRecibosHist = idFcabezalRecibosHist;
		this.idFcodigos = idFcodigos;
		this.orden = orden;
		this.descripcion = descripcion;
		this.sumaResta = sumaResta;
		this.cantidad = cantidad;
		this.importe = importe;
		this.moneda = moneda;
		this.registro = registro;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFHaberesHist", unique = true, nullable = false)
	public Long getIdFhaberesHist() {
		return this.idFhaberesHist;
	}

	public void setIdFhaberesHist(Long idFhaberesHist) {
		this.idFhaberesHist = idFhaberesHist;
	}

	@Column(name = "idGPlanta", nullable = false)
	public long getIdGplanta() {
		return this.idGplanta;
	}

	public void setIdGplanta(long idGplanta) {
		this.idGplanta = idGplanta;
	}

	@Column(name = "Tarjeta")
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "MesLiquidacion", length = 6)
	@Size(max = 6)
	public String getMesLiquidacion() {
		return this.mesLiquidacion;
	}

	public void setMesLiquidacion(String mesLiquidacion) {
		this.mesLiquidacion = mesLiquidacion;
	}

	@Column(name = "idFCabezalRecibosHist")
	public Integer getIdFCabezalRecibosHist() {
		return idFCabezalRecibosHist;
	}

	public void setIdFCabezalRecibosHist(Integer idFcabezalRecibosHist) {
		this.idFCabezalRecibosHist = idFcabezalRecibosHist;
	}

	@Column(name = "idFCodigos")
	public Short getIdFcodigos() {
		return this.idFcodigos;
	}

	public void setIdFcodigos(Short idFcodigos) {
		this.idFcodigos = idFcodigos;
	}

	@Column(name = "Orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "Descripcion", length = 50)
	@Size(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SumaResta")
	public Short getSumaResta() {
		return this.sumaResta;
	}

	public void setSumaResta(Short sumaResta) {
		this.sumaResta = sumaResta;
	}

	@Column(name = "Cantidad")
	public Short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Short cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "Importe", precision = 8)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "Moneda", length = 7)
	@Size(max = 7)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "Registro")
	public Short getRegistro() {
		return this.registro;
	}

	public void setRegistro(Short registro) {
		this.registro = registro;
	}

}
