package uy.org.aladi.admrh.jpadomain.entities;

// Generated 12/08/2015 04:48:06 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Fhaberesliquidadostmp generated by hbm2java
 */
@Entity
@Table(name = "fhaberesliquidadostmp")
public class Fhaberesliquidadostmp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 109872212677997545L;
	private Long idFhaberesLiquidados;
	private Fcabezalrecibotmp fcabezalrecibotmp;
	private Long idGplanta;
	private Short tarjeta;
	private String mesLiquidacion;
	private Short idFcodigos;
	private Integer orden;
	private String descripcion;
	private Short sumaResta;
	private Short cantidad;
	private BigDecimal importe;
	private String moneda;
	private Short registro;

	public Fhaberesliquidadostmp() {
	}

	public Fhaberesliquidadostmp(Fcabezalrecibotmp fcabezalrecibotmp,
			Long idGplanta, Short idFcodigos) {
		this.fcabezalrecibotmp = fcabezalrecibotmp;
		this.idGplanta = idGplanta;
		this.idFcodigos = idFcodigos;
	}

	public Fhaberesliquidadostmp(Fcabezalrecibotmp fcabezalrecibotmp,
			Long idGplanta, Short tarjeta, String mesLiquidacion,
			Short idFcodigos, Integer orden, String descripcion,
			Short sumaResta, Short cantidad, BigDecimal importe, String moneda,
			Short registro) {
		this.fcabezalrecibotmp = fcabezalrecibotmp;
		this.idGplanta = idGplanta;
		this.tarjeta = tarjeta;
		this.mesLiquidacion = mesLiquidacion;
		this.idFcodigos = idFcodigos;
		this.orden = orden;
		this.descripcion = descripcion;
		this.sumaResta = sumaResta;
		this.cantidad = cantidad;
		this.importe = importe;
		this.moneda = moneda;
		this.registro = registro;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFHaberesLiquidados", unique = true, nullable = false)
	public Long getIdFhaberesLiquidados() {
		return this.idFhaberesLiquidados;
	}

	public void setIdFhaberesLiquidados(Long idFhaberesLiquidados) {
		this.idFhaberesLiquidados = idFhaberesLiquidados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFCabezalRecibos", nullable = false)
	@NotNull
	public Fcabezalrecibotmp getFcabezalrecibotmp() {
		return this.fcabezalrecibotmp;
	}

	public void setFcabezalrecibotmp(Fcabezalrecibotmp fcabezalrecibotmp) {
		this.fcabezalrecibotmp = fcabezalrecibotmp;
	}

	@Column(name = "idGPlanta", nullable = false)
	public Long getIdGplanta() {
		return this.idGplanta;
	}

	public void setIdGplanta(Long idGplanta) {
		this.idGplanta = idGplanta;
	}

	@Column(name = "Tarjeta")
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "MesLiquidacion", length = 6)
	@Size(max = 6)
	public String getMesLiquidacion() {
		return this.mesLiquidacion;
	}

	public void setMesLiquidacion(String mesLiquidacion) {
		this.mesLiquidacion = mesLiquidacion;
	}

	@Column(name = "idFCodigos", nullable = false)
	public Short getIdFcodigos() {
		return this.idFcodigos;
	}

	public void setIdFcodigos(Short idFcodigos) {
		this.idFcodigos = idFcodigos;
	}

	@Column(name = "Orden")
	public Integer getOrden() {
		return this.orden;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	@Column(name = "Descripcion", length = 50)
	@Size(max = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "SumaResta")
	public Short getSumaResta() {
		return this.sumaResta;
	}

	public void setSumaResta(Short sumaResta) {
		this.sumaResta = sumaResta;
	}

	@Column(name = "Cantidad")
	public Short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Short cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "Importe", precision = 8)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "Moneda", length = 7)
	@Size(max = 7)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "Registro")
	public Short getRegistro() {
		return this.registro;
	}

	public void setRegistro(Short registro) {
		this.registro = registro;
	}

}
