package uy.org.aladi.admrh.jpadomain.entities;
// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Finteresesdistrib generated by hbm2java
 */
@Entity
@Table(name="finteresesdistrib")
public class Finteresesdistrib  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8066730900510449876L;
	private Long idFinteresesDistrib;
     private Gplanta gplanta;
     private Short tarjeta;
     private String mesDistrib;
     private Short idFcodigos;
     private Integer orden;
     private String descripcion;
     private Short sumaResta;
     private Short cantidad;
     private BigDecimal importe;
     private String moneda;
     private Short registro;

    public Finteresesdistrib() {
    }

	
    public Finteresesdistrib(Long idFinteresesDistrib, Gplanta gplanta) {
        this.idFinteresesDistrib = idFinteresesDistrib;
        this.gplanta = gplanta;
    }
    public Finteresesdistrib(Long idFinteresesDistrib, Gplanta gplanta, Short tarjeta, String mesDistrib, Short idFcodigos, Integer orden, String descripcion, Short sumaResta, Short cantidad, BigDecimal importe, String moneda, Short registro) {
       this.idFinteresesDistrib = idFinteresesDistrib;
       this.gplanta = gplanta;
       this.tarjeta = tarjeta;
       this.mesDistrib = mesDistrib;
       this.idFcodigos = idFcodigos;
       this.orden = orden;
       this.descripcion = descripcion;
       this.sumaResta = sumaResta;
       this.cantidad = cantidad;
       this.importe = importe;
       this.moneda = moneda;
       this.registro = registro;
    }
   
     @Id 

    
    @Column(name="idFInteresesDistrib", unique=true, nullable=false)
    public Long getIdFinteresesDistrib() {
        return this.idFinteresesDistrib;
    }
    
    public void setIdFinteresesDistrib(Long idFinteresesDistrib) {
        this.idFinteresesDistrib = idFinteresesDistrib;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGPlanta", nullable=false)
    @NotNull
    public Gplanta getGplanta() {
        return this.gplanta;
    }
    
    public void setGplanta(Gplanta gplanta) {
        this.gplanta = gplanta;
    }

    
    @Column(name="Tarjeta")
    public Short getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Short tarjeta) {
        this.tarjeta = tarjeta;
    }

    
    @Column(name="MesDistrib", length=6)
    @Size(max=6)
    public String getMesDistrib() {
        return this.mesDistrib;
    }
    
    public void setMesDistrib(String mesDistrib) {
        this.mesDistrib = mesDistrib;
    }

    
    @Column(name="idFCodigos")
    public Short getIdFcodigos() {
        return this.idFcodigos;
    }
    
    public void setIdFcodigos(Short idFcodigos) {
        this.idFcodigos = idFcodigos;
    }

    
    @Column(name="Orden")
    public Integer getOrden() {
        return this.orden;
    }
    
    public void setOrden(Integer orden) {
        this.orden = orden;
    }

    
    @Column(name="Descripcion", length=50)
    @Size(max=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="SumaResta")
    public Short getSumaResta() {
        return this.sumaResta;
    }
    
    public void setSumaResta(Short sumaResta) {
        this.sumaResta = sumaResta;
    }

    
    @Column(name="Cantidad")
    public Short getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Short cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="Importe", precision=8)
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }

    
    @Column(name="Moneda", length=7)
    @Size(max=7)
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }

    
    @Column(name="Registro")
    public Short getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(Short registro) {
        this.registro = registro;
    }




}


