package uy.org.aladi.admrh.jpadomain.entities;

// Generated 14/09/2015 01:34:04 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Flogfondo generated by hbm2java
 */
@Entity
@Table(name = "flogfondo")
public class Flogfondo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5930461076817561172L;
	private Integer idFlogFondo;
	private Date fecha;
	private Date hora;
	private String usuario;
	private String categoria;
	private String procedimiento;
	private String tablasLeidas;
	private String tablasModif;

	public Flogfondo() {
	}

	public Flogfondo(Date fecha, String usuario) {
		this.fecha = fecha;
		this.usuario = usuario;
	}

	public Flogfondo(Date fecha, Date hora, String usuario, String categoria,
			String procedimiento, String tablasLeidas, String tablasModif) {
		this.fecha = fecha;
		this.hora = hora;
		this.usuario = usuario;
		this.categoria = categoria;
		this.procedimiento = procedimiento;
		this.tablasLeidas = tablasLeidas;
		this.tablasModif = tablasModif;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFlogFondo", unique = true, nullable = false)
	public Integer getIdFlogFondo() {
		return this.idFlogFondo;
	}

	public void setIdFlogFondo(Integer idFlogFondo) {
		this.idFlogFondo = idFlogFondo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha", nullable = false, length = 10)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "Hora", length = 8)
	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	@Column(name = "Usuario", nullable = false, length = 200)
	@NotNull
	@Size(max = 200)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "Categoria", length = 500)
	@Size(max = 500)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "Procedimiento", length = 500)
	@Size(max = 500)
	public String getProcedimiento() {
		return this.procedimiento;
	}

	public void setProcedimiento(String procedimiento) {
		this.procedimiento = procedimiento;
	}

	@Column(name = "TablasLeidas", length = 1000)
	@Size(max = 1000)
	public String getTablasLeidas() {
		return this.tablasLeidas;
	}

	public void setTablasLeidas(String tablasLeidas) {
		this.tablasLeidas = tablasLeidas;
	}

	@Column(name = "TablasModif", length = 500)
	@Size(max = 500)
	public String getTablasModif() {
		return this.tablasModif;
	}

	public void setTablasModif(String tablasModif) {
		this.tablasModif = tablasModif;
	}

}
