package uy.org.aladi.admrh.jpadomain.entities;
// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Fmovimientos generated by hbm2java
 */
@Entity
@Table(name="fmovimientos")
public class Fmovimientos  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 7087512453990762833L;
	private Long idFmovimientos;
     private Ftipomovimiento ftipomovimiento;
     private Gplanta gplanta;
     private Short tarjeta;
     private Date fechaMovimiento;
     private Long orden;
     private Short tipoMovimiento;
     private Integer nroPrestamo;
     private Short nroCuota;
     private BigDecimal importeMov;
     private BigDecimal importeCapSec;
     private BigDecimal importeIntFunc;
     private BigDecimal saldoAnterior;
     private BigDecimal saldoActual;
     private String mesLiquidacion;
     private String observaciones;

    public Fmovimientos() {
    }

	
    public Fmovimientos(Ftipomovimiento ftipomovimiento, Gplanta gplanta) {
        this.ftipomovimiento = ftipomovimiento;
        this.gplanta = gplanta;
    }
    public Fmovimientos(Ftipomovimiento ftipomovimiento, Gplanta gplanta, Short tarjeta, Date fechaMovimiento, Long orden, Short tipoMovimiento, Integer nroPrestamo, Short nroCuota, BigDecimal importeMov, BigDecimal importeCapSec, BigDecimal importeIntFunc, BigDecimal saldoAnterior, BigDecimal saldoActual, String mesLiquidacion, String observaciones) {
       this.ftipomovimiento = ftipomovimiento;
       this.gplanta = gplanta;
       this.tarjeta = tarjeta;
       this.fechaMovimiento = fechaMovimiento;
       this.orden = orden;
       this.tipoMovimiento = tipoMovimiento;
       this.nroPrestamo = nroPrestamo;
       this.nroCuota = nroCuota;
       this.importeMov = importeMov;
       this.importeCapSec = importeCapSec;
       this.importeIntFunc = importeIntFunc;
       this.saldoAnterior = saldoAnterior;
       this.saldoActual = saldoActual;
       this.mesLiquidacion = mesLiquidacion;
       this.observaciones = observaciones;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFMovimientos", unique=true, nullable=false)
    public Long getIdFmovimientos() {
        return this.idFmovimientos;
    }
    
    public void setIdFmovimientos(Long idFmovimientos) {
        this.idFmovimientos = idFmovimientos;
    }

@ManyToOne
    @JoinColumn(name="idFTipoMovimiento", nullable=false)
    @NotNull
    public Ftipomovimiento getFtipomovimiento() {
        return this.ftipomovimiento;
    }
    
    public void setFtipomovimiento(Ftipomovimiento ftipomovimiento) {
        this.ftipomovimiento = ftipomovimiento;
    }

@ManyToOne
    @JoinColumn(name="idGPlanta", nullable=false)
    @NotNull
    public Gplanta getGplanta() {
        return this.gplanta;
    }
    
    public void setGplanta(Gplanta gplanta) {
        this.gplanta = gplanta;
    }

    
    @Column(name="Tarjeta")
    public Short getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Short tarjeta) {
        this.tarjeta = tarjeta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaMovimiento", length=10)
    public Date getFechaMovimiento() {
        return this.fechaMovimiento;
    }
    
    public void setFechaMovimiento(Date fechaMovimiento) {
        this.fechaMovimiento = fechaMovimiento;
    }

    
    @Column(name="Orden")
    public Long getOrden() {
        return this.orden;
    }
    
    public void setOrden(Long orden) {
        this.orden = orden;
    }

    
    @Column(name="TipoMovimiento")
    public Short getTipoMovimiento() {
        return this.tipoMovimiento;
    }
    
    public void setTipoMovimiento(Short tipoMovimiento) {
        this.tipoMovimiento = tipoMovimiento;
    }

    
    @Column(name="NroPrestamo")
    public Integer getNroPrestamo() {
        return this.nroPrestamo;
    }
    
    public void setNroPrestamo(Integer nroPrestamo) {
        this.nroPrestamo = nroPrestamo;
    }

    
    @Column(name="NroCuota")
    public Short getNroCuota() {
        return this.nroCuota;
    }
    
    public void setNroCuota(Short nroCuota) {
        this.nroCuota = nroCuota;
    }

    
    @Column(name="ImporteMov", precision=10)
    public BigDecimal getImporteMov() {
        return this.importeMov;
    }
    
    public void setImporteMov(BigDecimal importeMov) {
        this.importeMov = importeMov;
    }

    
    @Column(name="ImporteCapSec", precision=10)
    public BigDecimal getImporteCapSec() {
        return this.importeCapSec;
    }
    
    public void setImporteCapSec(BigDecimal importeCapSec) {
        this.importeCapSec = importeCapSec;
    }

    
    @Column(name="ImporteIntFunc", precision=10)
    public BigDecimal getImporteIntFunc() {
        return this.importeIntFunc;
    }
    
    public void setImporteIntFunc(BigDecimal importeIntFunc) {
        this.importeIntFunc = importeIntFunc;
    }

    
    @Column(name="SaldoAnterior", precision=10)
    public BigDecimal getSaldoAnterior() {
        return this.saldoAnterior;
    }
    
    public void setSaldoAnterior(BigDecimal saldoAnterior) {
        this.saldoAnterior = saldoAnterior;
    }

    
    @Column(name="SaldoActual", precision=10)
    public BigDecimal getSaldoActual() {
        return this.saldoActual;
    }
    
    public void setSaldoActual(BigDecimal saldoActual) {
        this.saldoActual = saldoActual;
    }

    
    @Column(name="MesLiquidacion", length=6)
    @Size(max=6)
    public String getMesLiquidacion() {
        return this.mesLiquidacion;
    }
    
    public void setMesLiquidacion(String mesLiquidacion) {
        this.mesLiquidacion = mesLiquidacion;
    }

    
    @Column(name="Observaciones", length=60)
    @Size(max=60)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }




}


