package uy.org.aladi.admrh.jpadomain.entities;
// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Fmutualistasplanes generated by hbm2java
 */
@Entity
@Table(name="fmutualistasplanes")
public class Fmutualistasplanes  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 9165196412077337598L;
	private Integer idFmutualistasPlanes;
     private Fmutualistas fmutualistas;
     private String nombrePlan;
     private BigDecimal valorCuota;
     private String codigoAnterior;
     private Boolean especial;
     private List<Gcargas> gcargas = new ArrayList<Gcargas>(0);
     private List<Gplanta> gplanta = new ArrayList<Gplanta>(0);
     private List<Fafiliaciones> fafiliaciones = new ArrayList<Fafiliaciones>(0);

    public Fmutualistasplanes() {
    }

	
    public Fmutualistasplanes(Fmutualistas fmutualistas, String nombrePlan, BigDecimal valorCuota) {
        this.fmutualistas = fmutualistas;
        this.nombrePlan = nombrePlan;
        this.valorCuota = valorCuota;
    }
    public Fmutualistasplanes(Fmutualistas fmutualistas, String nombrePlan, BigDecimal valorCuota, 
    		String codigoAnterior, Boolean especial,  List<Gplanta> gplantas, List<Gcargas> gcargas,
    		List<Fafiliaciones> fafiliacioneses) {
       this.fmutualistas = fmutualistas;
       this.nombrePlan = nombrePlan;
       this.valorCuota = valorCuota;
       this.codigoAnterior = codigoAnterior;
       this.especial = especial;
       this.gcargas = gcargas;
       this.gplanta = gplantas;
       this.fafiliaciones = fafiliacioneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFMutualistasPlanes", unique=true, nullable=false)
    public Integer getIdFmutualistasPlanes() {
        return this.idFmutualistasPlanes;
    }
    
    public void setIdFmutualistasPlanes(Integer idFmutualistasPlanes) {
        this.idFmutualistasPlanes = idFmutualistasPlanes;
    }

    @ManyToOne
    @JoinColumn(name="idFMutualistas", nullable=false)
    @NotNull
    public Fmutualistas getFmutualistas() {
        return this.fmutualistas;
    }
    
    public void setFmutualistas(Fmutualistas fmutualistas) {
        this.fmutualistas = fmutualistas;
    }

    
    @Column(name="NombrePlan", nullable=false, length=60)
    @NotNull
    @Size(max=60)
    public String getNombrePlan() {
        return this.nombrePlan;
    }
    
    public void setNombrePlan(String nombrePlan) {
        this.nombrePlan = nombrePlan;
    }

    
    @Column(name="ValorCuota", nullable=false, precision=8)
    @NotNull
    public BigDecimal getValorCuota() {
        return this.valorCuota;
    }
    
    public void setValorCuota(BigDecimal valorCuota) {
        this.valorCuota = valorCuota;
    }

    
    @Column(name="CodigoAnterior", length=4)
    @Size(max=4)
    public String getCodigoAnterior() {
        return this.codigoAnterior;
    }
    
    public void setCodigoAnterior(String codigoAnterior) {
        this.codigoAnterior = codigoAnterior;
    }

    
    @Column(name="Especial")
    public Boolean getEspecial() {
        return this.especial;
    }
    
    public void setEspecial(Boolean especial) {
        this.especial = especial;
    }


    @OneToMany(mappedBy="fmutualistasplanes")
    public List<Gcargas> getGcargas() {
        return this.gcargas;
    }
    
    public void setGcargas(List<Gcargas> gcargas) {
        this.gcargas = gcargas;
    }  

    @OneToMany(mappedBy="fmutualistasplanes")
    public List<Gplanta> getGplanta() {
        return this.gplanta;
    }
    
    public void setGplanta(List<Gplanta> gplantas) {
        this.gplanta = gplantas;
    }

    @OneToMany(mappedBy="fmutualistasplanes")
    public List<Fafiliaciones> getFafiliaciones() {
        return this.fafiliaciones;
    }
    
    public void setFafiliaciones(List<Fafiliaciones> fafiliacioneses) {
        this.fafiliaciones = fafiliacioneses;
    }




}


