package uy.org.aladi.admrh.jpadomain.entities;

// Generated 07/01/2015 12:18:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * Fparamfuncionario generated by hbm2java
 */
@Entity
@Table(name = "fparamfuncionario")
public class Fparamfuncionario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1740936540213557895L;
	private Long idFparamFuncionario;
	private Gplanta gplanta;
	private short tarjeta;
	private Fparametros fparametros;
	private Short cantidad;
	private Date fechaDesde;
	private Date fechaHasta;
	private Short idFcodigos;


	public Fparamfuncionario() {
	}

	public Fparamfuncionario(Gplanta gplanta, short tarjeta,
			Fparametros fparametros) {
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
		this.fparametros = fparametros;
	}

	public Fparamfuncionario(Gplanta gplanta, short tarjeta,
			Fparametros fparametros, Short cantidad, Date fechaDesde,
			Date fechaHasta, Short idFcodigos) {
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
		this.fparametros = fparametros;
		this.cantidad = cantidad;
		this.fechaDesde = fechaDesde;
		this.fechaHasta = fechaHasta;
		this.idFcodigos = idFcodigos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFParamFuncionario", unique = true, nullable = false)
	public Long getIdFparamFuncionario() {
		return this.idFparamFuncionario;
	}

	public void setIdFparamFuncionario(Long idFparamFuncionario) {
		this.idFparamFuncionario = idFparamFuncionario;
	}

	@ManyToOne
	@JoinColumn(name = "idGPlanta", nullable = false)
	@NotNull
	public Gplanta getGplanta() {
		return this.gplanta;
	}

	public void setGplanta(Gplanta gplanta) {
		this.gplanta = gplanta;
	}

	@Column(name = "Tarjeta", nullable = false)
	public short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@ManyToOne
	@JoinColumn(name = "idFParametros", nullable = false)
	@NotNull
	public Fparametros getFparametros() {
		return this.fparametros;
	}

	public void setFparametros(Fparametros fparametros) {
		this.fparametros = fparametros;
	}

	@Column(name = "Cantidad")
	public Short getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Short cantidad) {
		this.cantidad = cantidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaDesde", length = 10)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaHasta", length = 10)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

	@Column(name = "idFCodigos")
	public Short getIdFcodigos() {
		return idFcodigos;
	}

	public void setIdFcodigos(Short idFcodigos) {
		this.idFcodigos = idFcodigos;
	}

}
