package uy.org.aladi.admrh.jpadomain.entities;

// Generated 22/12/2014 01:22:29 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Size;

/**
 * Fparametros generated by hbm2java
 */
@Entity
@Table(name = "fparametros")
public class Fparametros implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5031301058625156110L;
	private Long idFparametros;
	private Short idFcodigos;
	private String descripcion;
	private BigDecimal valorParametro;
	private String simbolo;
	private List<Fparamfuncionario> fparamfuncionarios = new ArrayList<Fparamfuncionario>();

	public Fparametros() {
	}

	public Fparametros(Short idFcodigos, String descripcion,
			BigDecimal valorParametro, String simbolo, List<Fparamfuncionario> fparamfuncionarios) {
		this.idFcodigos = idFcodigos;
		this.descripcion = descripcion;
		this.valorParametro = valorParametro;
		this.simbolo = simbolo;
		this.fparamfuncionarios = fparamfuncionarios;
	}

	@Id
	@Column(name = "idFParametros", unique = true, nullable = false)
	public Long getIdFparametros() {
		return this.idFparametros;
	}

	public void setIdFparametros(Long idFparametros) {
		this.idFparametros = idFparametros;
	}

	@Column(name = "idFCodigos")
	public Short getIdFcodigos() {
		return this.idFcodigos;
	}

	public void setIdFcodigos(Short idFcodigos) {
		this.idFcodigos = idFcodigos;
	}

	@Column(name = "Descripcion", length = 500)
	@Size(max = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ValorParametro", precision = 8)
	public BigDecimal getValorParametro() {
		return this.valorParametro;
	}

	public void setValorParametro(BigDecimal valorParametro) {
		this.valorParametro = valorParametro;
	}

	@Column(name = "Simbolo", length = 3)
	@Size(max = 3)
	public String getSimbolo() {
		return this.simbolo;
	}

	public void setSimbolo(String simbolo) {
		this.simbolo = simbolo;
	}

	@OneToMany(mappedBy = "fparametros")
	public List<Fparamfuncionario> getFparamfuncionarios() {
		return fparamfuncionarios;
	}

	public void setFparamfuncionarios(List<Fparamfuncionario> fparamfuncionarios) {
		this.fparamfuncionarios = fparamfuncionarios;
	}

}
