package uy.org.aladi.admrh.jpadomain.entities;

// Generated 07/01/2015 11:35:34 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fparametroshist generated by hbm2java
 */
@Entity
@Table(name = "fparametroshist")
public class Fparametroshist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6414777357253927350L;
	private Long idFparametrosHist;
	private Long idFparametros;
	private Date fechaDesde;
	private BigDecimal valorParametro;
	private Date fechaHasta;

	public Fparametroshist() {
	}

	public Fparametroshist(Long idFparametros) {
		this.idFparametros = idFparametros;
	}

	public Fparametroshist(Long idFparametros, Date fechaDesde,
			BigDecimal valorParametro, Date fechaHasta) {
		this.idFparametros = idFparametros;
		this.fechaDesde = fechaDesde;
		this.valorParametro = valorParametro;
		this.fechaHasta = fechaHasta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFParametrosHist", unique = true, nullable = false)
	public Long getIdFparametrosHist() {
		return this.idFparametrosHist;
	}

	public void setIdFparametrosHist(Long idFparametrosHist) {
		this.idFparametrosHist = idFparametrosHist;
	}

	@Column(name = "idFparametros", nullable = false)
	public Long getIdFparametros() {
		return this.idFparametros;
	}

	public void setIdFparametros(Long idFparametros) {
		this.idFparametros = idFparametros;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaDesde", length = 10)
	public Date getFechaDesde() {
		return this.fechaDesde;
	}

	public void setFechaDesde(Date fechaDesde) {
		this.fechaDesde = fechaDesde;
	}

	@Column(name = "ValorParametro", precision = 8)
	public BigDecimal getValorParametro() {
		return this.valorParametro;
	}

	public void setValorParametro(BigDecimal valorParametro) {
		this.valorParametro = valorParametro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaHasta", length = 10)
	public Date getFechaHasta() {
		return this.fechaHasta;
	}

	public void setFechaHasta(Date fechaHasta) {
		this.fechaHasta = fechaHasta;
	}

}
