package uy.org.aladi.admrh.jpadomain.entities;

// Generated 28/10/2014 11:03:17 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Fprestamosconsumohist generated by hbm2java
 */
@Entity
@Table(name = "fprestamosconsumohist", uniqueConstraints = @UniqueConstraint(columnNames = "NroPrestamo"))
public class Fprestamosconsumohist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8028631917883246026L;
	private Integer idFprestamosConsumoHist;
	private Integer nroPrestamo;
	private Long idGplanta;
	private Short tarjeta;
	private Date fechaPrestamo;
	private BigDecimal capitalPrestamo;
	private BigDecimal interesPrestamo;
	private BigDecimal cuota;
	private Short cantCuotas;
	private Short cuotasPagas;
	private BigDecimal saldoPrestamo;
	private Date fechaSaldo;
	private Boolean prestamoNuevo;

	public Fprestamosconsumohist() {
	}

	public Fprestamosconsumohist(Integer idFprestamosConsumoHist, Long idGplanta) {
		this.idFprestamosConsumoHist = idFprestamosConsumoHist;
		this.idGplanta = idGplanta;
	}

	public Fprestamosconsumohist(Integer idFprestamosConsumoHist,
			Integer nroPrestamo, Long idGplanta, Short tarjeta,
			Date fechaPrestamo, BigDecimal capitalPrestamo,
			BigDecimal interesPrestamo, BigDecimal cuota, Short cantCuotas,
			Short cuotasPagas, BigDecimal saldoPrestamo, Date fechaSaldo,
			Boolean prestamoNuevo) {
		this.idFprestamosConsumoHist = idFprestamosConsumoHist;
		this.nroPrestamo = nroPrestamo;
		this.idGplanta = idGplanta;
		this.tarjeta = tarjeta;
		this.fechaPrestamo = fechaPrestamo;
		this.capitalPrestamo = capitalPrestamo;
		this.interesPrestamo = interesPrestamo;
		this.cuota = cuota;
		this.cantCuotas = cantCuotas;
		this.cuotasPagas = cuotasPagas;
		this.saldoPrestamo = saldoPrestamo;
		this.fechaSaldo = fechaSaldo;
		this.prestamoNuevo = prestamoNuevo;
	}

    @Id @GeneratedValue(strategy=IDENTITY)

	@Column(name = "idFPrestamosConsumoHist", unique = true, nullable = false)
	public Integer getIdFprestamosConsumoHist() {
		return this.idFprestamosConsumoHist;
	}

	public void setIdFprestamosConsumoHist(Integer idFprestamosConsumoHist) {
		this.idFprestamosConsumoHist = idFprestamosConsumoHist;
	}

	@Column(name = "NroPrestamo", unique = true)
	public Integer getNroPrestamo() {
		return this.nroPrestamo;
	}

	public void setNroPrestamo(Integer nroPrestamo) {
		this.nroPrestamo = nroPrestamo;
	}

	@Column(name = "idGPlanta", nullable = false)
	public Long getIdGplanta() {
		return this.idGplanta;
	}

	public void setIdGplanta(Long idGplanta) {
		this.idGplanta = idGplanta;
	}

	@Column(name = "Tarjeta")
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaPrestamo", length = 10)
	public Date getFechaPrestamo() {
		return this.fechaPrestamo;
	}

	public void setFechaPrestamo(Date fechaPrestamo) {
		this.fechaPrestamo = fechaPrestamo;
	}

	@Column(name = "CapitalPrestamo", precision = 10)
	public BigDecimal getCapitalPrestamo() {
		return this.capitalPrestamo;
	}

	public void setCapitalPrestamo(BigDecimal capitalPrestamo) {
		this.capitalPrestamo = capitalPrestamo;
	}

	@Column(name = "InteresPrestamo", precision = 6)
	public BigDecimal getInteresPrestamo() {
		return this.interesPrestamo;
	}

	public void setInteresPrestamo(BigDecimal interesPrestamo) {
		this.interesPrestamo = interesPrestamo;
	}

	@Column(name = "Cuota", precision = 8)
	public BigDecimal getCuota() {
		return this.cuota;
	}

	public void setCuota(BigDecimal cuota) {
		this.cuota = cuota;
	}

	@Column(name = "CantCuotas")
	public Short getCantCuotas() {
		return this.cantCuotas;
	}

	public void setCantCuotas(Short cantCuotas) {
		this.cantCuotas = cantCuotas;
	}

	@Column(name = "CuotasPagas")
	public Short getCuotasPagas() {
		return this.cuotasPagas;
	}

	public void setCuotasPagas(Short cuotasPagas) {
		this.cuotasPagas = cuotasPagas;
	}

	@Column(name = "SaldoPrestamo", precision = 10)
	public BigDecimal getSaldoPrestamo() {
		return this.saldoPrestamo;
	}

	public void setSaldoPrestamo(BigDecimal saldoPrestamo) {
		this.saldoPrestamo = saldoPrestamo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaSaldo", length = 10)
	public Date getFechaSaldo() {
		return this.fechaSaldo;
	}

	public void setFechaSaldo(Date fechaSaldo) {
		this.fechaSaldo = fechaSaldo;
	}

	@Column(name = "PrestamoNuevo")
	public Boolean getPrestamoNuevo() {
		return this.prestamoNuevo;
	}

	public void setPrestamoNuevo(Boolean prestamoNuevo) {
		this.prestamoNuevo = prestamoNuevo;
	}

}
