package uy.org.aladi.admrh.jpadomain.entities;

// Generated 20/10/2014 11:53:58 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Fresultadosdistribucion generated by hbm2java
 */
@Entity
@Table(name = "fresultadosdistribucion")
public class Fresultadosdistribucion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2739503452602428607L;
	private Long idFresultadosDistribucion;
	private Gplanta gplanta;
	private Short tarjeta;
	private Date fecha;
	private String mesInicial;
	private String mesFinal;
	private String mesLiquidacion;
	private Fcodigos fcodigos;
	private BigDecimal totalAdistribuir;
	private BigDecimal numeralesFuncionario;
	private BigDecimal numeralesTodos;
	private BigDecimal pctFuncionario;
	private BigDecimal distribucionFuncionario;

	public Fresultadosdistribucion() {
	}

	public Fresultadosdistribucion(Long idFresultadosDistribucion) {
		this.idFresultadosDistribucion = idFresultadosDistribucion;
	}

	public Fresultadosdistribucion(Long idFresultadosDistribucion,
			Gplanta gplanta, Short tarjeta, Date fecha, String mesInicial,
			String mesFinal, String mesLiquidacion, Fcodigos fcodigos,
			BigDecimal totalAdistribuir, BigDecimal numeralesFuncionario,
			BigDecimal numeralesTodos, BigDecimal pctFuncionario, BigDecimal distribucionFuncionario) {
		this.idFresultadosDistribucion = idFresultadosDistribucion;
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
		this.fecha = fecha;
		this.mesInicial = mesInicial;
		this.mesFinal = mesFinal;
		this.mesLiquidacion = mesLiquidacion;
		this.fcodigos = fcodigos;
		this.totalAdistribuir = totalAdistribuir;
		this.numeralesFuncionario = numeralesFuncionario;
		this.numeralesTodos = numeralesTodos;
		this.pctFuncionario = pctFuncionario;
		this.distribucionFuncionario = distribucionFuncionario;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFResultadosDistribucion", unique = true, nullable = false)
	public Long getIdFresultadosDistribucion() {
		return this.idFresultadosDistribucion;
	}

	public void setIdFresultadosDistribucion(Long idFresultadosDistribucion) {
		this.idFresultadosDistribucion = idFresultadosDistribucion;
	}

	@ManyToOne
    @JoinColumn(name="idGPlanta", nullable=false)
    @NotNull
    public Gplanta getGplanta() {
        return this.gplanta;
    }
    
    public void setGplanta(Gplanta gplanta) {
        this.gplanta = gplanta;
    }


	@Column(name = "Tarjeta")
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha", length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "MesInicial", length = 6)
	@Size(max = 6)
	public String getMesInicial() {
		return this.mesInicial;
	}

	public void setMesInicial(String mesInicial) {
		this.mesInicial = mesInicial;
	}

	@Column(name = "MesFinal", length = 6)
	@Size(max = 6)
	public String getMesFinal() {
		return this.mesFinal;
	}

	public void setMesFinal(String mesFinal) {
		this.mesFinal = mesFinal;
	}

	@Column(name = "MesLiquidacion", length = 6)
	@Size(max = 6)
	public String getMesLiquidacion() {
		return this.mesLiquidacion;
	}

	public void setMesLiquidacion(String mesLiquidacion) {
		this.mesLiquidacion = mesLiquidacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idFCodigos")
	public Fcodigos getFcodigos() {
		return this.fcodigos;
	}

	public void setFcodigos(Fcodigos fcodigos) {
		this.fcodigos = fcodigos;
	}

	@Column(name = "TotalADistribuir", precision = 8)
	public BigDecimal getTotalAdistribuir() {
		return this.totalAdistribuir;
	}

	public void setTotalAdistribuir(BigDecimal totalAdistribuir) {
		this.totalAdistribuir = totalAdistribuir;
	}

	@Column(name = "NumeralesFuncionario", precision = 8)
	public BigDecimal getNumeralesFuncionario() {
		return this.numeralesFuncionario;
	}

	public void setNumeralesFuncionario(BigDecimal numeralesFuncionario) {
		this.numeralesFuncionario = numeralesFuncionario;
	}

	@Column(name = "NumeralesTodos", precision = 8)
	public BigDecimal getNumeralesTodos() {
		return this.numeralesTodos;
	}

	public void setNumeralesTodos(BigDecimal numeralesTodos) {
		this.numeralesTodos = numeralesTodos;
	}

	@Column(name = "PctFuncionario", precision = 8)
	public BigDecimal getPctFuncionario() {
		return pctFuncionario;
	}

	public void setPctFuncionario(BigDecimal pctFuncionario) {
		this.pctFuncionario = pctFuncionario;
	}

	@Column(name = "DistribucionFuncionario", precision = 8)
	public BigDecimal getDistribucionFuncionario() {
		return this.distribucionFuncionario;
	}

	public void setDistribucionFuncionario(BigDecimal distribucionFuncionario) {
		this.distribucionFuncionario = distribucionFuncionario;
	}


}
