package uy.org.aladi.admrh.jpadomain.entities;
// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

/**
 * Fsaldoshistoria generated by hbm2java
 */
@Entity
@Table(name="fsaldoshistoria", uniqueConstraints = @UniqueConstraint(columnNames={"Tarjeta", "Fecha"}) 
)
public class Fsaldoshistoria  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1149337304808299789L;
	private Long idFsaldosHistoria;
     private Long idGplanta;
     private Short tarjeta;
     private Date fecha;
     private BigDecimal capitalIntegAntes;
     private BigDecimal capitalIntegActual;
     private BigDecimal capitalDispAntes;
     private BigDecimal capitalDispActual;
     private BigDecimal numerales;
     private String mesLiquidacion;

    public Fsaldoshistoria() {
    }

	
    public Fsaldoshistoria(Long idGplanta) {
        this.idGplanta = idGplanta;
    }
    public Fsaldoshistoria(Long idGplanta, Short tarjeta, Date fecha, BigDecimal capitalIntegAntes, BigDecimal capitalIntegActual, BigDecimal capitalDispAntes, BigDecimal capitalDispActual, BigDecimal numerales, String mesLiquidacion) {
       this.idGplanta = idGplanta;
       this.tarjeta = tarjeta;
       this.fecha = fecha;
       this.capitalIntegAntes = capitalIntegAntes;
       this.capitalIntegActual = capitalIntegActual;
       this.capitalDispAntes = capitalDispAntes;
       this.capitalDispActual = capitalDispActual;
       this.numerales = numerales;
       this.mesLiquidacion = mesLiquidacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFSaldosHistoria", unique=true, nullable=false)
    public Long getIdFsaldosHistoria() {
        return this.idFsaldosHistoria;
    }
    
    public void setIdFsaldosHistoria(Long idFsaldosHistoria) {
        this.idFsaldosHistoria = idFsaldosHistoria;
    }

    
    @Column(name="idGPlanta", nullable=false)
    public Long getIdGplanta() {
        return this.idGplanta;
    }
    
    public void setIdGplanta(Long idGplanta) {
        this.idGplanta = idGplanta;
    }

    
    @Column(name="Tarjeta")
    public Short getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Short tarjeta) {
        this.tarjeta = tarjeta;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="CapitalIntegAntes", precision=10)
    public BigDecimal getCapitalIntegAntes() {
        return this.capitalIntegAntes;
    }
    
    public void setCapitalIntegAntes(BigDecimal capitalIntegAntes) {
        this.capitalIntegAntes = capitalIntegAntes;
    }

    
    @Column(name="CapitalIntegActual", precision=10)
    public BigDecimal getCapitalIntegActual() {
        return this.capitalIntegActual;
    }
    
    public void setCapitalIntegActual(BigDecimal capitalIntegActual) {
        this.capitalIntegActual = capitalIntegActual;
    }

    
    @Column(name="CapitalDispAntes", precision=10)
    public BigDecimal getCapitalDispAntes() {
        return this.capitalDispAntes;
    }
    
    public void setCapitalDispAntes(BigDecimal capitalDispAntes) {
        this.capitalDispAntes = capitalDispAntes;
    }

    
    @Column(name="CapitalDispActual", precision=10)
    public BigDecimal getCapitalDispActual() {
        return this.capitalDispActual;
    }
    
    public void setCapitalDispActual(BigDecimal capitalDispActual) {
        this.capitalDispActual = capitalDispActual;
    }

    
    @Column(name="Numerales", precision=10)
    public BigDecimal getNumerales() {
        return this.numerales;
    }
    
    public void setNumerales(BigDecimal numerales) {
        this.numerales = numerales;
    }

    
    @Column(name="MesLiquidacion", length=6)
    @Size(max=6)
    public String getMesLiquidacion() {
        return this.mesLiquidacion;
    }
    
    public void setMesLiquidacion(String mesLiquidacion) {
        this.mesLiquidacion = mesLiquidacion;
    }




}


