package uy.org.aladi.admrh.jpadomain.entities;
// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

/**
 * Fsaldosacum generated by hbm2java
 */
@Entity
@Table(name="fsaldosacum", uniqueConstraints = @UniqueConstraint(columnNames="Tarjeta") 
)
public class Fsaldosacum  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 5750940612228303425L;
	private Integer idFsaldosAcum;
     private Gplanta gplanta;
     private Short tarjeta;
     private BigDecimal saldosPrestAcumulado;
     private Date fecha;

    public Fsaldosacum() {
    }

	
    public Fsaldosacum(Gplanta gplanta) {
        this.gplanta = gplanta;
    }
    public Fsaldosacum(Gplanta gplanta, Short tarjeta, BigDecimal saldosPrestAcumulado, Date fecha) {
       this.gplanta = gplanta;
       this.tarjeta = tarjeta;
       this.saldosPrestAcumulado = saldosPrestAcumulado;
       this.fecha = fecha;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFSaldosAcum", unique=true, nullable=false)
    public Integer getIdFsaldosAcum() {
        return this.idFsaldosAcum;
    }
    
    public void setIdFsaldosAcum(Integer idFsaldosAcum) {
        this.idFsaldosAcum = idFsaldosAcum;
    }

    
    @OneToOne
    @JoinColumn(name="idGPlanta", nullable=false)
    @NotNull
    public Gplanta getGplanta() {
        return this.gplanta;
    }
    
    public void setGplanta(Gplanta gplanta) {
        this.gplanta = gplanta;
    }

    
    @Column(name="Tarjeta", unique=true)
    public Short getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Short tarjeta) {
        this.tarjeta = tarjeta;
    }

    
    @Column(name="SaldosPrestAcumulado", precision=10)
    public BigDecimal getSaldosPrestAcumulado() {
        return this.saldosPrestAcumulado;
    }
    
    public void setSaldosPrestAcumulado(BigDecimal saldosPrestAcumulado) {
        this.saldosPrestAcumulado = saldosPrestAcumulado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fecha", length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


