package uy.org.aladi.admrh.jpadomain.entities;

// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Fsueldomes generated by hbm2java
 */
@Entity
@Table(name = "fsueldomes", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "Tarjeta", "AnioMes" })})
public class Fsueldomes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8317787313427079689L;
	private Long idFsueldoMes;
	private Gplanta gplanta;
	private Short tarjeta;
	private String anioMes;
	private Date fecha;
	private BigDecimal sueldomes;
	private String motivo;

	public Fsueldomes() {
	}

	public Fsueldomes(Gplanta gplanta, Short tarjeta, String anioMes,
			Date fecha, BigDecimal sueldomes, String motivo) {
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
		this.anioMes = anioMes;
		this.fecha = fecha;
		this.sueldomes = sueldomes;
		this.motivo = motivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFSueldoMes", unique = true, nullable = false)
	public Long getIdFsueldoMes() {
		return this.idFsueldoMes;
	}

	public void setIdFsueldoMes(Long idFsueldoMes) {
		this.idFsueldoMes = idFsueldoMes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGPlanta", nullable = false)
	@NotNull
	public Gplanta getGplanta() {
		return this.gplanta;
	}

	public void setGplanta(Gplanta gplanta) {
		this.gplanta = gplanta;
	}

	@Column(name = "Tarjeta", nullable = false)
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "AnioMes", nullable = false, length = 6)
	@NotNull
	@Size(max = 6)
	public String getAnioMes() {
		return this.anioMes;
	}

	public void setAnioMes(String anioMes) {
		this.anioMes = anioMes;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Fecha", nullable = false, length = 19)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "Sueldomes", nullable = false, precision = 8)
	@NotNull
	public BigDecimal getSueldomes() {
		return this.sueldomes;
	}

	public void setSueldomes(BigDecimal sueldomes) {
		this.sueldomes = sueldomes;
	}

	@Column(name = "Motivo", nullable = false, length = 100)
	@NotNull
	@Size(max = 100)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

}
