package uy.org.aladi.admrh.jpadomain.entities;

// Generated 17/04/2015 04:02:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

/**
 * Gbajacargas generated by hbm2java
 */
@Entity
@Table(name = "gbajacargas")
public class Gbajacargas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7480733354793007775L;
	private Integer idGbajaCargas;
	private Long idGplanta;
	private Short tarjeta;
	private Short nroFamiliar;
	private String nombreFamiliar;
	private String parentesco;
	private Date nacimiento;
	private Boolean discapacitado;
	private String sexo;
	private Integer idFmutualistasPlanes;
	private String codigomutual;
	private Integer nroSocio;
	private Boolean reembolso;
	private Boolean afaladiSs;
	private Boolean fonasa;

	public Gbajacargas() {
	}

	public Gbajacargas(long idGplanta, short tarjeta) {
		this.idGplanta = idGplanta;
		this.tarjeta = tarjeta;
	}

	public Gbajacargas(Long idGplanta, Short tarjeta, Short nroFamiliar,
			String nombreFamiliar, String parentesco, Date nacimiento,
			Boolean discapacitado, String sexo, Integer idFmutualistasPlanes,
			String codigomutual, Integer nroSocio, Boolean reembolso,
			Boolean afaladiSs, Boolean fonasa) {
		this.idGplanta = idGplanta;
		this.tarjeta = tarjeta;
		this.nroFamiliar = nroFamiliar;
		this.nombreFamiliar = nombreFamiliar;
		this.parentesco = parentesco;
		this.nacimiento = nacimiento;
		this.discapacitado = discapacitado;
		this.sexo = sexo;
		this.idFmutualistasPlanes = idFmutualistasPlanes;
		this.codigomutual = codigomutual;
		this.nroSocio = nroSocio;
		this.reembolso = reembolso;
		this.afaladiSs = afaladiSs;
		this.fonasa = fonasa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGBajaCargas", unique = true, nullable = false)
	public Integer getIdGbajaCargas() {
		return this.idGbajaCargas;
	}

	public void setIdGbajaCargas(Integer idGbajaCargas) {
		this.idGbajaCargas = idGbajaCargas;
	}

	@Column(name = "idGplanta", nullable = false)
	public Long getIdGplanta() {
		return this.idGplanta;
	}

	public void setIdGplanta(Long idGplanta) {
		this.idGplanta = idGplanta;
	}

	@Column(name = "Tarjeta", nullable = false)
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "NroFamiliar")
	public Short getNroFamiliar() {
		return this.nroFamiliar;
	}

	public void setNroFamiliar(Short nroFamiliar) {
		this.nroFamiliar = nroFamiliar;
	}

	@Column(name = "NombreFamiliar", length = 50)
	@Size(max = 50)
	public String getNombreFamiliar() {
		return this.nombreFamiliar;
	}

	public void setNombreFamiliar(String nombreFamiliar) {
		this.nombreFamiliar = nombreFamiliar;
	}

	@Column(name = "Parentesco", length = 15)
	@Size(max = 15)
	public String getParentesco() {
		return this.parentesco;
	}

	public void setParentesco(String parentesco) {
		this.parentesco = parentesco;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Nacimiento", length = 10)
	public Date getNacimiento() {
		return this.nacimiento;
	}

	public void setNacimiento(Date nacimiento) {
		this.nacimiento = nacimiento;
	}

	@Column(name = "Discapacitado")
	public Boolean getDiscapacitado() {
		return this.discapacitado;
	}

	public void setDiscapacitado(Boolean discapacitado) {
		this.discapacitado = discapacitado;
	}

	@Column(name = "Sexo")
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "idFMutualistasPlanes")
	public Integer getIdFmutualistasPlanes() {
		return this.idFmutualistasPlanes;
	}

	public void setIdFmutualistasPlanes(Integer idFmutualistasPlanes) {
		this.idFmutualistasPlanes = idFmutualistasPlanes;
	}

	@Column(name = "codigomutual", length = 4)
	@Size(max = 4)
	public String getCodigomutual() {
		return this.codigomutual;
	}

	public void setCodigomutual(String codigomutual) {
		this.codigomutual = codigomutual;
	}

	@Column(name = "NroSocio")
	public Integer getNroSocio() {
		return this.nroSocio;
	}

	public void setNroSocio(Integer nroSocio) {
		this.nroSocio = nroSocio;
	}

	@Column(name = "Reembolso")
	public Boolean getReembolso() {
		return this.reembolso;
	}

	public void setReembolso(Boolean reembolso) {
		this.reembolso = reembolso;
	}

	@Column(name = "AfaladiSS")
	public Boolean getAfaladiSs() {
		return this.afaladiSs;
	}

	public void setAfaladiSs(Boolean afaladiSs) {
		this.afaladiSs = afaladiSs;
	}

	@Column(name = "Fonasa")
	public Boolean getFonasa() {
		return this.fonasa;
	}

	public void setFonasa(Boolean fonasa) {
		this.fonasa = fonasa;
	}

}
