package uy.org.aladi.admrh.jpadomain.entities;

// Generated 22/12/2014 01:00:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Gcargas generated by hbm2java
 */
@Entity
@Table(name = "gcargas")
public class Gcargas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2146080681224949208L;
	private Integer idGcargas;
	private Gplanta gplanta;
	private short tarjeta;
	private Short nroFamiliar;
	private String nombreFamiliar;
	private String parentesco;
	private Date nacimiento;
	private Boolean discapacitado;
	private String sexo;
	private Fmutualistasplanes fmutualistasplanes;
	private String codigomutual;
	private Integer nroSocio;
	private Boolean reembolso;
	private Boolean afaladiSs;
	private Boolean fonasa;

	public Gcargas() {
	}

	public Gcargas(Gplanta gplanta, short tarjeta) {
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
	}

	public Gcargas(Gplanta gplanta, short tarjeta, Short nroFamiliar,
			String nombreFamiliar, String parentesco, Date nacimiento,
			Boolean discapacitado, String sexo, Fmutualistasplanes fmutualistasplanes,
			String codigomutual, Integer nroSocio, Boolean reembolso,
			Boolean afaladiSs, Boolean fonasa) {
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
		this.nroFamiliar = nroFamiliar;
		this.nombreFamiliar = nombreFamiliar;
		this.parentesco = parentesco;
		this.nacimiento = nacimiento;
		this.discapacitado = discapacitado;
		this.sexo = sexo;
		this.fmutualistasplanes = fmutualistasplanes;
		this.codigomutual = codigomutual;
		this.nroSocio = nroSocio;
		this.reembolso = reembolso;
		this.afaladiSs = afaladiSs;
		this.fonasa = fonasa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGCargas", unique = true, nullable = false)
	public Integer getIdGcargas() {
		return this.idGcargas;
	}

	public void setIdGcargas(Integer idGcargas) {
		this.idGcargas = idGcargas;
	}

	@ManyToOne
    @JoinColumn(name="idGPlanta", nullable=false)
    @NotNull
    public Gplanta getGplanta() {
        return this.gplanta;
    }
    
    public void setGplanta(Gplanta gplanta) {
        this.gplanta = gplanta;
    }


	@Column(name = "Tarjeta", nullable = false)
	public short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "NroFamiliar")
	public Short getNroFamiliar() {
		return this.nroFamiliar;
	}

	public void setNroFamiliar(Short nroFamiliar) {
		this.nroFamiliar = nroFamiliar;
	}

	@Column(name = "NombreFamiliar", length = 50)
	@Size(max = 50)
	public String getNombreFamiliar() {
		return this.nombreFamiliar;
	}

	public void setNombreFamiliar(String nombreFamiliar) {
		this.nombreFamiliar = nombreFamiliar;
	}

	@Column(name = "Parentesco", length = 15)
	@Size(max = 15)
	public String getParentesco() {
		return this.parentesco;
	}

	public void setParentesco(String parentesco) {
		this.parentesco = parentesco;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Nacimiento", length = 10)
	public Date getNacimiento() {
		return this.nacimiento;
	}

	public void setNacimiento(Date nacimiento) {
		this.nacimiento = nacimiento;
	}

	@Column(name = "Discapacitado")
	public Boolean getDiscapacitado() {
		return this.discapacitado;
	}

	public void setDiscapacitado(Boolean discapacitado) {
		this.discapacitado = discapacitado;
	}

	@Column(name = "Sexo", length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}


	@Column(name = "codigomutual", length = 4)
	@Size(max = 4)
	public String getCodigomutual() {
		return this.codigomutual;
	}

	public void setCodigomutual(String codigomutual) {
		this.codigomutual = codigomutual;
	}

	@Column(name = "NroSocio")
	public Integer getNroSocio() {
		return this.nroSocio;
	}

	public void setNroSocio(Integer nroSocio) {
		this.nroSocio = nroSocio;
	}

	@Column(name = "Reembolso")
	public Boolean getReembolso() {
		return this.reembolso;
	}

	public void setReembolso(Boolean reembolso) {
		this.reembolso = reembolso;
	}

	@Column(name = "AfaladiSS")
	public Boolean getAfaladiSs() {
		return this.afaladiSs;
	}

	public void setAfaladiSs(Boolean afaladiSs) {
		this.afaladiSs = afaladiSs;
	}

	@Column(name = "Fonasa")
	public Boolean getFonasa() {
		return this.fonasa;
	}

	public void setFonasa(Boolean fonasa) {
		this.fonasa = fonasa;
	}

	@ManyToOne
    @JoinColumn(name="idFMutualistasPlanes", nullable=true)
	public Fmutualistasplanes getFmutualistasplanes() {
		return fmutualistasplanes;
	}

	public void setFmutualistasplanes(Fmutualistasplanes fmutualistasplanes) {
		this.fmutualistasplanes = fmutualistasplanes;
	}

}
