package uy.org.aladi.admrh.jpadomain.entities;
// Generated 14/10/2014 11:19:54 AM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

/**
 * Gparametros generated by hbm2java
 */
@Entity
@Table(name="gparametros")
public class Gparametros  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -7243790718422609021L;
	private Integer idgparametros;
     private Short gcodigo;
     private String svalor;
     private BigDecimal nvalor;
     private String descripcion;
     private Date fechaActualizacion;

    public Gparametros() {
    }

    public Gparametros(Short gcodigo, String svalor, BigDecimal nvalor, String descripcion, Date fechaActualizacion) {
       this.gcodigo = gcodigo;
       this.svalor = svalor;
       this.nvalor = nvalor;
       this.descripcion = descripcion;
       this.fechaActualizacion = fechaActualizacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idgparametros", unique=true, nullable=false)
    public Integer getIdgparametros() {
        return this.idgparametros;
    }
    
    public void setIdgparametros(Integer idgparametros) {
        this.idgparametros = idgparametros;
    }

    
    @Column(name="gcodigo")
    public Short getGcodigo() {
        return this.gcodigo;
    }
    
    public void setGcodigo(Short gcodigo) {
        this.gcodigo = gcodigo;
    }

    
    @Column(name="svalor", length=45)
    @Size(max=45)
    public String getSvalor() {
        return this.svalor;
    }
    
    public void setSvalor(String svalor) {
        this.svalor = svalor;
    }

    
    @Column(name="nvalor", precision=8)
    public BigDecimal getNvalor() {
        return this.nvalor;
    }
    
    public void setNvalor(BigDecimal nvalor) {
        this.nvalor = nvalor;
    }

    
    @Column(name="descripcion")
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaActualizacion", length=10)
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


