package uy.org.aladi.admrh.jpadomain.entities;
// Generated 20/11/2014 01:32:38 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Size;

/**
 * Gplantahist generated by hbm2java
 */
@Entity
@Table(name="gplantahist", uniqueConstraints = @UniqueConstraint(columnNames="Tarjeta") 
)
public class Gplantahist  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1297837513642976094L;
	private Long idGplantaHist;
     private Short tarjeta;
     private String nombre;
     private String documento;
     private String nacionalidad;
     private Date ingreso;
     private Date egreso;
     private Integer idGcategoria;
     private Short idGgrados;
     private Integer idBcoMdoCobro;
     private String ctacte;
     private Integer idFmutualistasPlanes;
     private String nroSocio;
     private Boolean reembolso;
     private Boolean marcas;
     private Short idGorganigrama;
     private Boolean ultimoIngreso;
     private Boolean egresoFinanzas;
     private Boolean ultimoEgreso;
     private Date fechaNacimiento;
     private Boolean cambioSueldoMes;
     private String sexo;

    public Gplantahist() {
    }

	
    public Gplantahist(Short tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Gplantahist(Short tarjeta, String nombre, String documento, String nacionalidad, Date ingreso, Date egreso, Integer idGcategoria, Short idGgrados, Integer idBcoMdoCobro, String ctacte, Integer idFmutualistasPlanes, String nroSocio, Boolean reembolso, Boolean marcas, Short idGorganigrama, Boolean ultimoIngreso, Boolean egresoFinanzas, Boolean ultimoEgreso, Date fechaNacimiento, Boolean cambioSueldoMes, String sexo) {
       this.tarjeta = tarjeta;
       this.nombre = nombre;
       this.documento = documento;
       this.nacionalidad = nacionalidad;
       this.ingreso = ingreso;
       this.egreso = egreso;
       this.idGcategoria = idGcategoria;
       this.idGgrados = idGgrados;
       this.idBcoMdoCobro = idBcoMdoCobro;
       this.ctacte = ctacte;
       this.idFmutualistasPlanes = idFmutualistasPlanes;
       this.nroSocio = nroSocio;
       this.reembolso = reembolso;
       this.marcas = marcas;
       this.idGorganigrama = idGorganigrama;
       this.ultimoIngreso = ultimoIngreso;
       this.egresoFinanzas = egresoFinanzas;
       this.ultimoEgreso = ultimoEgreso;
       this.fechaNacimiento = fechaNacimiento;
       this.cambioSueldoMes = cambioSueldoMes;
       this.sexo = sexo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
   
    @Column(name="idGPlantaHist", unique=true, nullable=false)
    public Long getIdGplantaHist() {
        return this.idGplantaHist;
    }
    
    public void setIdGplantaHist(Long idGplantaHist) {
        this.idGplantaHist = idGplantaHist;
    }

    
    @Column(name="Tarjeta", unique=true, nullable=false)
    public Short getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Short tarjeta) {
        this.tarjeta = tarjeta;
    }

    
    @Column(name="Nombre", length=30)
    @Size(max=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Documento", length=20)
    @Size(max=20)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }

    
    @Column(name="Nacionalidad", length=15)
    @Size(max=15)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Ingreso", length=10)
    public Date getIngreso() {
        return this.ingreso;
    }
    
    public void setIngreso(Date ingreso) {
        this.ingreso = ingreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Egreso", length=10)
    public Date getEgreso() {
        return this.egreso;
    }
    
    public void setEgreso(Date egreso) {
        this.egreso = egreso;
    }

    
    @Column(name="idGCategoria")
    public Integer getIdGcategoria() {
        return this.idGcategoria;
    }
    
    public void setIdGcategoria(Integer idGcategoria) {
        this.idGcategoria = idGcategoria;
    }

    
    @Column(name="idGGrados")
    public Short getIdGgrados() {
        return this.idGgrados;
    }
    
    public void setIdGgrados(Short idGgrados) {
        this.idGgrados = idGgrados;
    }

    
    @Column(name="idBcoMdoCobro")
    public Integer getIdBcoMdoCobro() {
        return this.idBcoMdoCobro;
    }
    
    public void setIdBcoMdoCobro(Integer idBcoMdoCobro) {
        this.idBcoMdoCobro = idBcoMdoCobro;
    }

    
    @Column(name="Ctacte", length=10)
    @Size(max=10)
    public String getCtacte() {
        return this.ctacte;
    }
    
    public void setCtacte(String ctacte) {
        this.ctacte = ctacte;
    }

    
    @Column(name="idFMutualistasPlanes")
    public Integer getIdFmutualistasPlanes() {
        return this.idFmutualistasPlanes;
    }
    
    public void setIdFmutualistasPlanes(Integer idFmutualistasPlanes) {
        this.idFmutualistasPlanes = idFmutualistasPlanes;
    }

    
    @Column(name="NroSocio", length=10)
    @Size(max=10)
    public String getNroSocio() {
        return this.nroSocio;
    }
    
    public void setNroSocio(String nroSocio) {
        this.nroSocio = nroSocio;
    }

    
    @Column(name="Reembolso")
    public Boolean getReembolso() {
        return this.reembolso;
    }
    
    public void setReembolso(Boolean reembolso) {
        this.reembolso = reembolso;
    }

    
    @Column(name="Marcas")
    public Boolean getMarcas() {
        return this.marcas;
    }
    
    public void setMarcas(Boolean marcas) {
        this.marcas = marcas;
    }

    
    @Column(name="idGOrganigrama")
    public Short getIdGorganigrama() {
        return this.idGorganigrama;
    }
    
    public void setIdGorganigrama(Short idGorganigrama) {
        this.idGorganigrama = idGorganigrama;
    }

    
    @Column(name="UltimoIngreso")
    public Boolean getUltimoIngreso() {
        return this.ultimoIngreso;
    }
    
    public void setUltimoIngreso(Boolean ultimoIngreso) {
        this.ultimoIngreso = ultimoIngreso;
    }

    
    @Column(name="EgresoFinanzas")
    public Boolean getEgresoFinanzas() {
        return this.egresoFinanzas;
    }
    
    public void setEgresoFinanzas(Boolean egresoFinanzas) {
        this.egresoFinanzas = egresoFinanzas;
    }

    
    @Column(name="UltimoEgreso")
    public Boolean getUltimoEgreso() {
        return this.ultimoEgreso;
    }
    
    public void setUltimoEgreso(Boolean ultimoEgreso) {
        this.ultimoEgreso = ultimoEgreso;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="FechaNacimiento", length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    
    @Column(name="CambioSueldoMes")
    public Boolean getCambioSueldoMes() {
        return this.cambioSueldoMes;
    }
    
    public void setCambioSueldoMes(Boolean cambioSueldoMes) {
        this.cambioSueldoMes = cambioSueldoMes;
    }

    
    @Column(name="Sexo", length=1)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


