package uy.org.aladi.admrh.jpadomain.entities;

// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Rajustehis generated by hbm2java
 */
@Entity
@Table(name = "rajustehis")
public class Rajustehis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5134671745178308403L;
	private Integer idRajusteHis;
	private Long idGplanta;
	private Short tarjeta;
	private String mesAjuste;
	private String mesCierre;
	private String tipoCierre;
	private Short pasaDe;
	private Short pasaA;
	private Short dias;
	private String horas;
	private Date fechadesde;
	private Date fechahasta;

	public Rajustehis() {
	}

	public Rajustehis(Integer idRajusteHis, Long idGplanta, Short tarjeta,
			String mesAjuste, String mesCierre, String tipoCierre, Short pasaDe,
			Short pasaA, Short dias, String horas, Date fechadesde, Date fechahasta) {
		this.idRajusteHis = idRajusteHis;
		this.idGplanta = idGplanta;
		this.tarjeta = tarjeta;
		this.mesAjuste = mesAjuste;
		this.mesCierre = mesCierre;
		this.tipoCierre = tipoCierre;
		this.pasaDe = pasaDe;
		this.pasaA = pasaA;
		this.dias = dias;
		this.horas = horas;
		this.setFechadesde(fechadesde);
		this.setFechahasta(fechahasta);
	}

	@Id
	@Column(name = "idRAjusteHis", unique = true, nullable = false)
	public Integer getIdRajusteHis() {
		return this.idRajusteHis;
	}

	public void setIdRajusteHis(Integer idRajusteHis) {
		this.idRajusteHis = idRajusteHis;
	}

	@Column(name = "idGPlanta", nullable = false)
	public Long getIdGplanta() {
		return this.idGplanta;
	}

	public void setIdGplanta(Long idGplanta) {
		this.idGplanta = idGplanta;
	}

	@Column(name = "Tarjeta", nullable = false)
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Column(name = "MesAjuste", nullable = false, length = 6)
	@NotNull
	@Size(max = 6)
	public String getMesAjuste() {
		return this.mesAjuste;
	}

	public void setMesAjuste(String mesAjuste) {
		this.mesAjuste = mesAjuste;
	}

	@Column(name = "MesCierre", nullable = false, length = 6)
	@NotNull
	@Size(max = 6)
	public String getMesCierre() {
		return this.mesCierre;
	}

	public void setMesCierre(String mesCierre) {
		this.mesCierre = mesCierre;
	}

	@Column(name = "TipoCierre", nullable = false, length = 1)
	public String getTipoCierre() {
		return this.tipoCierre;
	}

	public void setTipoCierre(String tipoCierre) {
		this.tipoCierre = tipoCierre;
	}

	@Column(name = "PasaDe", nullable = false)
	public Short getPasaDe() {
		return this.pasaDe;
	}

	public void setPasaDe(Short pasaDe) {
		this.pasaDe = pasaDe;
	}

	@Column(name = "PasaA", nullable = false)
	public Short getPasaA() {
		return this.pasaA;
	}

	public void setPasaA(Short pasaA) {
		this.pasaA = pasaA;
	}

	@Column(name = "Dias", nullable = false)
	public Short getDias() {
		return this.dias;
	}

	public void setDias(Short dias) {
		this.dias = dias;
	}

	@Column(name = "Horas")
	public String getHoras() {
		return this.horas;
	}

	public void setHoras(String horas) {
		this.horas = horas;
	}

	@Column(name="FechaDesde")
	public Date getFechadesde() {
		return fechadesde;
	}

	public void setFechadesde(Date fechadesde) {
		this.fechadesde = fechadesde;
	}

	@Column(name="FechaHasta")
	public Date getFechahasta() {
		return fechahasta;
	}

	public void setFechahasta(Date fechahasta) {
		this.fechahasta = fechahasta;
	}


}
