package uy.org.aladi.admrh.jpadomain.entities;

// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * Rausenteh generated by hbm2java
 */
@Entity
@Table(name = "rausenteh")
public class Rausenteh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4882989061449963940L;
	private Integer idRausenteH;
	private Long idGplanta;
	private Short tarjeta;
	private Date fechac;
	private Date fechaf;
	private Short idRcodigos;
	private String motivo;

	public Rausenteh() {
	}

	public Rausenteh(Long idGplanta, Short tarjeta, Date fechac, Date fechaf,
			String motivo) {
		this.idGplanta = idGplanta;
		this.tarjeta = tarjeta;
		this.fechac = fechac;
		this.fechaf = fechaf;
		this.motivo = motivo;
	}

	public Rausenteh(Long idGplanta, Short tarjeta, Date fechac, Date fechaf,
			Short idRcodigos, String motivo) {
		this.idGplanta = idGplanta;
		this.tarjeta = tarjeta;
		this.fechac = fechac;
		this.fechaf = fechaf;
		this.idRcodigos = idRcodigos;
		this.motivo = motivo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRAusenteH", unique = true, nullable = false)
	public Integer getIdRausenteH() {
		return this.idRausenteH;
	}

	public void setIdRausenteH(Integer idRausenteH) {
		this.idRausenteH = idRausenteH;
	}

	@Column(name = "idGPlanta", nullable = false)
	public Long getIdGplanta() {
		return this.idGplanta;
	}

	public void setIdGplanta(Long idGplanta) {
		this.idGplanta = idGplanta;
	}

	@Column(name = "Tarjeta", nullable = false)
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fechac", nullable = false, length = 10)
	@NotNull
	public Date getFechac() {
		return this.fechac;
	}

	public void setFechac(Date fechac) {
		this.fechac = fechac;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fechaf", nullable = false, length = 10)
	@NotNull
	public Date getFechaf() {
		return this.fechaf;
	}

	public void setFechaf(Date fechaf) {
		this.fechaf = fechaf;
	}

	@Column(name = "idRCodigos")
	public Short getIdRcodigos() {
		return this.idRcodigos;
	}

	public void setIdRcodigos(Short idRcodigos) {
		this.idRcodigos = idRcodigos;
	}

	@Column(name = "Motivo", nullable = false)
	@NotNull
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

}
