package uy.org.aladi.admrh.jpadomain.entities;
// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * Rausentes generated by hbm2java
 */
@Entity
@Table(name="rausentes")
public class Rausentes  implements java.io.Serializable {


	private static final long serialVersionUID = 606054606893169175L;
	private Long idRausentes;
     private Rcodigos rcodigos;
     private Gplanta gplanta;
     private Short tarjeta;
     private String nombre;
     private Date fechac;
     private Date fechaf;
     private String motivo;

    public Rausentes() {
    }

	
    public Rausentes(Gplanta gplanta, Short tarjeta, Date fechac, String motivo) {
        this.gplanta = gplanta;
        this.tarjeta = tarjeta;
        this.fechac = fechac;
        this.motivo = motivo;
    }
    public Rausentes(Rcodigos rcodigos, Gplanta gplanta, Short tarjeta, Date fechac, Date fechaf, String motivo) {
       this.rcodigos = rcodigos;
       this.gplanta = gplanta;
       this.tarjeta = tarjeta;
       this.fechac = fechac;
       this.fechaf = fechaf;
       this.motivo = motivo;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)    
    @Column(name="idRAusentes", unique=true, nullable=false)
    public Long getIdRausentes() {
        return this.idRausentes;
    }
    
    public void setIdRausentes(Long idRausentes) {
        this.idRausentes = idRausentes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idRCodigos")
    public Rcodigos getRcodigos() {
        return this.rcodigos;
    }
    
    public void setRcodigos(Rcodigos rcodigos) {
        this.rcodigos = rcodigos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idGPlanta", nullable=false)
    @NotNull
    public Gplanta getGplanta() {
        return this.gplanta;
    }
    
    public void setGplanta(Gplanta gplanta) {
        this.gplanta = gplanta;
    }

    
    @Column(name="Tarjeta", nullable=false)
    public Short getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Short tarjeta) {
        this.tarjeta = tarjeta;
    }

    @Column(name="Nombre")
    public String getNombre() {
		return nombre;
	}


	public void setNombre(String nombre) {
		this.nombre = nombre;
	}


	@Temporal(TemporalType.DATE)
    @Column(name="Fechac", nullable=false, length=10)
    @NotNull
    public Date getFechac() {
        return this.fechac;
    }
    
    public void setFechac(Date fechac) {
        this.fechac = fechac;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Fechaf", length=10)
    public Date getFechaf() {
        return this.fechaf;
    }
    
    public void setFechaf(Date fechaf) {
        this.fechaf = fechaf;
    }

    
    @Column(name="Motivo", nullable=false)
    @NotNull
    public String getMotivo() {
        return this.motivo;
    }
    
    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }




}


