package uy.org.aladi.admrh.jpadomain.entities;

// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Rferiados generated by hbm2java
 */
@Entity
@Table(name = "rferiados")
public class Rferiados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8597615795269508974L;
	private Integer idRferiados;
	private Date fecha;
	private String motivo;
	private Boolean doble;

	public Rferiados() {
	}

	public Rferiados(Date fecha, String motivo, Boolean doble) {
		this.fecha = fecha;
		this.motivo = motivo;
		this.doble = doble;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRFeriados", unique = true, nullable = false)
	public Integer getIdRferiados() {
		return this.idRferiados;
	}

	public void setIdRferiados(Integer idRferiados) {
		this.idRferiados = idRferiados;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha", nullable = false, length = 10)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "Motivo", nullable = false, length = 25)
	@NotNull
	@Size(max = 25)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "Doble", nullable = false)
	public Boolean isDoble() {
		return this.doble;
	}

	public void setDoble(Boolean doble) {
		this.doble = doble;
	}

}
