package uy.org.aladi.admrh.jpadomain.entities;

// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Rmarcorighis generated by hbm2java
 */
@Entity
@Table(name = "rmarcorighis")
public class Rmarcorighis implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2077586901619230359L;
	private Integer idRmarcorighis;
	private String tarjeta;
	private Date fecha;
	private String hora;
	private String tipo;
	private Integer adm;
	private String deadm;
	private String vigente;
	private String control;

	public Rmarcorighis() {
	}

	public Rmarcorighis(String tarjeta, Date fecha, String hora, String tipo,
			Integer adm, String deadm, String vigente, String control) {
		this.tarjeta = tarjeta;
		this.fecha = fecha;
		this.hora = hora;
		this.tipo = tipo;
		this.adm = adm;
		this.deadm = deadm;
		this.vigente = vigente;
		this.control = control;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRMarcorighis", unique = true, nullable = false)
	public Integer getIdRmarcorighis() {
		return this.idRmarcorighis;
	}

	public void setIdRmarcorighis(Integer idRmarcorighis) {
		this.idRmarcorighis = idRmarcorighis;
	}

	@Column(name = "Tarjeta", nullable = false, length = 10)
	@NotNull
	@Size(max = 10)
	public String getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(String tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha", nullable = false, length = 10)
	@NotNull
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "Hora", nullable = false, length = 5)
	@NotNull
	@Size(max = 5)
	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	@Column(name = "Tipo", nullable = false, length = 2)
	@NotNull
	@Size(max = 2)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "adm", nullable = false)
	public Integer getAdm() {
		return this.adm;
	}

	public void setAdm(Integer adm) {
		this.adm = adm;
	}

	@Column(name = "Deadm", nullable = false, length = 2)
	@NotNull
	@Size(max = 2)
	public String getDeadm() {
		return this.deadm;
	}

	public void setDeadm(String deadm) {
		this.deadm = deadm;
	}

	@Column(name = "Vigente", nullable = false, length = 2)
	@NotNull
	@Size(max = 2)
	public String getVigente() {
		return this.vigente;
	}

	public void setVigente(String vigente) {
		this.vigente = vigente;
	}

	@Column(name = "Control", nullable = false, length = 2)
	@NotNull
	@Size(max = 2)
	public String getControl() {
		return this.control;
	}

	public void setControl(String control) {
		this.control = control;
	}

}
