package uy.org.aladi.admrh.jpadomain.entities;

// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1

import java.sql.Time;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * Rmarcames generated by hbm2java
 */
@Entity
@Table(name = "rmarcames")
public class Rmarcames implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8048084981928947017L;
	private Integer idRmarcames;
	private Rcodigos rcodigos;
	private Gplanta gplanta;
	private Short tarjeta;
	private Date fecha1;
	private Time hora1;
	private Date fecha2;
	private Time hora2;
	private String observ;
	private Boolean ultlect;
	private Date fechaAnalisis;

	public Rmarcames() {
	}

	public Rmarcames(Short tarjeta, Date fecha1, Time hora1){
		this.tarjeta = tarjeta;
		this.fecha1 = fecha1;
		this.hora1 = hora1;		
	}
	
	public Rmarcames(Rcodigos rcodigos, Gplanta gplanta, Short tarjeta,
			Date fecha1, Time hora1, Date fecha2, Time hora2, Boolean ultlect) {
		this.rcodigos = rcodigos;
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
		this.fecha1 = fecha1;
		this.hora1 = hora1;
		this.fecha2 = fecha2;
		this.hora2 = hora2;
		this.ultlect = ultlect;
	}

	public Rmarcames(Rcodigos rcodigos, Gplanta gplanta, Short tarjeta,
			Date fecha1, Time hora1, Date fecha2, Time hora2, String observ, Boolean ultlect,
			Date fechaAnalisis) {
		this.rcodigos = rcodigos;
		this.gplanta = gplanta;
		this.tarjeta = tarjeta;
		this.fecha1 = fecha1;
		this.hora1 = hora1;
		this.fecha2 = fecha2;
		this.hora2 = hora2;
		this.observ = observ;
		this.ultlect = ultlect;
		this.fechaAnalisis = fechaAnalisis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRmarcames", unique = true, nullable = false)
	public Integer getIdRmarcames() {
		return this.idRmarcames;
	}

	public void setIdRmarcames(Integer idRmarcames) {
		this.idRmarcames = idRmarcames;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRCodigos", nullable = false)
	@NotNull
	public Rcodigos getRcodigos() {
		return this.rcodigos;
	}

	public void setRcodigos(Rcodigos rcodigos) {
		this.rcodigos = rcodigos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idGPlanta", nullable = false)
	@NotNull
	public Gplanta getGplanta() {
		return this.gplanta;
	}

	public void setGplanta(Gplanta gplanta) {
		this.gplanta = gplanta;
	}

	@Column(name = "Tarjeta", nullable = false)
	public Short getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Short tarjeta) {
		this.tarjeta = tarjeta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha1")
	@NotNull
	public Date getFecha1() {
		return this.fecha1;
	}

	public void setFecha1(Date fecha1) {
		this.fecha1 = fecha1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Fecha2")
	public Date getFecha2() {
		return this.fecha2;
	}

	public void setFecha2(Date fecha2) {
		this.fecha2 = fecha2;
	}

	@Column(name = "observ", length = 45)
	@Size(max = 45)
	public String getObserv() {
		return this.observ;
	}

	public void setObserv(String observ) {
		this.observ = observ;
	}

	@Column(name = "Ultlect", nullable = false)
	public Boolean isUltlect() {
		return this.ultlect;
	}

	public void setUltlect(Boolean ultlect) {
		this.ultlect = ultlect;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaAnalisis", length = 19)
	public Date getFechaAnalisis() {
		return this.fechaAnalisis;
	}

	public void setFechaAnalisis(Date fechaAnalisis) {
		this.fechaAnalisis = fechaAnalisis;
	}

	@Column(name="Hora1")
	public Time getHora1() {
		return hora1;
	}

	public void setHora1(Time hora1) {
		this.hora1 = hora1;
	}

	@Column(name="Hora2")
	public Time getHora2() {
		return hora2;
	}

	public void setHora2(Time hora2) {
		this.hora2 = hora2;
	}

}
