package uy.org.aladi.admrh.jpadomain.entities;

// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol")
public class Rol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3293628265431016627L;
	private Long idRol;
	private String descripcion;
	private String descPublic;
	private List<UsuarioRol> usuarioRols = new ArrayList<UsuarioRol>(0);

	public Rol() {
	}

	public Rol(String descripcion, List<UsuarioRol> usuarioRols) {
		this.descripcion = descripcion;
		this.usuarioRols = usuarioRols;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_rol", unique = true, nullable = false)
	public Long getIdRol() {
		return this.idRol;
	}

	public void setIdRol(Long idRol) {
		this.idRol = idRol;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "descPublic")
	public String getDescPublic() {
		return descPublic;
	}

	public void setDescPublic(String descPublic) {
		this.descPublic = descPublic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public List<UsuarioRol> getUsuarioRols() {
		return this.usuarioRols;
	}

	public void setUsuarioRols(List<UsuarioRol> usuarioRols) {
		this.usuarioRols = usuarioRols;
	}


}
