package uy.org.aladi.admrh.jpadomain.entities;

// Generated 06/10/2014 08:58:58 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name = "usuario_rol")
public class UsuarioRol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8633616817033381077L;
	private Long idusuarioRol;
	private Usuario usuario;
	private Rol rol;

	public UsuarioRol() {
	}

	public UsuarioRol(Usuario usuario, Rol rol) {
		this.usuario = usuario;
		this.rol = rol;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idusuario_rol", unique = true, nullable = false)
	public Long getIdusuarioRol() {
		return this.idusuarioRol;
	}

	public void setIdusuarioRol(Long idusuarioRol) {
		this.idusuarioRol = idusuarioRol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol")
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

}
